# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg.proto',
  package='RL',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tmsg.proto\x12\x02RL\"H\n\x07\x44\x61taSet\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\x16\n\x0ejoint_position\x18\x02 \x03(\x02\x12\x16\n\x0ejoint_velocity\x18\x03 \x03(\x02\x62\x06proto3'
)




_DATASET = _descriptor.Descriptor(
  name='DataSet',
  full_name='RL.DataSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='RL.DataSet.count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='joint_position', full_name='RL.DataSet.joint_position', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='joint_velocity', full_name='RL.DataSet.joint_velocity', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['DataSet'] = _DATASET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataSet = _reflection.GeneratedProtocolMessageType('DataSet', (_message.Message,), {
  'DESCRIPTOR' : _DATASET,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:RL.DataSet)
  })
_sym_db.RegisterMessage(DataSet)


# @@protoc_insertion_point(module_scope)
